site_name: TableRise Docs
site_description: Documentação oficial do TableRise
site_url: https://docs.tablerise.com
site_author: TableRise

repo_name: GitHub
repo_url: https://github.com/TableRise/docs

nav:
  - Home: index.md
  - Contribua:
      - Guia: contribute/guide.md
      - Documentação: contribute/docs.md
      - Design: contribute/design.md
      - Frontend: contribute/frontend.md
      - Backend: contribute/backend.md
      - Testes: contribute/tests.md
      - Tradução: contribute/translation.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    admonition:
      type: material/alert-circle
  logo: assets/tablerise.png
  favicon: assets/tablerise.png

  palette:
    # default palette
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: black
      accent: deep purple

    # dark mode palette
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: black
      accent: deep purple

  features:
    - navigation.footer
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TableRise

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - i18n:
      docs_structure: folder
      languages:
        # default language, do not remove
        - locale: pt
          default: true
          name: Português
          build: true

        # translations
        - locale: en
          name: English
          build: true
          nav:
            - Home: index.md
            - Contribute:
                - Guide: contribute/guide.md
                - Documentation: contribute/docs.md
                - Design: contribute/design.md
                - Frontend: contribute/frontend.md
                - Backend: contribute/backend.md
                - Tests: contribute/tests.md
                - Translation: contribute/translation.md

        # add more languages below this line
